title: asymmetric's blagh
description: > # this means to ignore newlines until "baseurl:"
        This is my blagh
url: "http://asymmetric.github.io" # the base hostname & protocol for your site
github_username:  asymmetric

permalink: pretty
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Session.vim
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
